### ISSUE TITLE
1.1.0 can not install under zk1.4.2 ci build 140

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#64] opened 2016-03-21 19:59 UTC
Catchable Fatal Error: Argument 2 passed to Zikula\Common\Translator\Translator::__f() must be of the type array, string given, called in /home/www/pggo.koester123.de/Zikula_Core-1.4.2/system/ExtensionsModule/Helper/ExtensionHelper.php on line 318 and defined
500 Internal Server Error - ContextErrorException
Stack Trace

    in lib/Zikula/Common/Translator/Translator.php at line 253  -
             * @param null $locale
             * @return string
             */
            public function __f($msg, array $param, $domain = null, $locale = null)
            {
                return $this->trans($msg, $param, $domain, $locale);
            }
    at ErrorHandler ->handleError ('4096', 'Argument 2 passed to Zikula\Common\Translator\Translator::__f() must be of the type array, string given, called in /home/www/pggo.koester123.de/Zikula_Core-1.4.2/system/ExtensionsModule/Helper/ExtensionHelper.php on line 318 and defined', '/home/www/pggo.koester123.de/Zikula_Core-1.4.2/lib/Zikula/Common/Translator/Translator.php', '253', array('msg' => '%s must implement ExtensionInstallerInterface'))
    in lib/Zikula/Common/Translator/Translator.php at line 253  +
    at Translator ->__f ('%s must implement ExtensionInstallerInterface', 'Cmfcmf\Module\MediaModule\MediaModuleInstaller')
    in system/ExtensionsModule/Helper/ExtensionHelper.php at line 318  +
    at ExtensionHelper ->getExtensionInstallerInstance (object(CmfcmfMediaModule))
    in system/ExtensionsModule/Helper/ExtensionHelper.php at line 81  +
    at ExtensionHelper ->install (object(ExtensionEntity))
    in system/ExtensionsModule/Controller/ModuleController.php at line 273  +
    at ModuleController ->installAction (object(Zikula_Request_Http), object(ExtensionEntity))
    at call_user_func_array (array(object(ModuleController), 'installAction'), array(object(Zikula_Request_Http), object(ExtensionEntity)))
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 139  +
    at HttpKernel ->handleRaw (object(Zikula_Request_Http), '1')
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 62  +
    at HttpKernel ->handle (object(Zikula_Request_Http), '1', true)
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69  +
    at ContainerAwareHttpKernel ->handle (object(Zikula_Request_Http), '1', true)
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 185  +
    at Kernel ->handle (object(Zikula_Request_Http))
    in index.php at line 25  +

**Comment by craigh** [comment] 2016-03-21 20:59
the error is in the core and now fixed. But it appears that maybe there is also an issue with `Cmfcmf\Module\MediaModule\MediaModuleInstaller` not implementing `ExtensionInstallerInterface` ?

**Comment by cmfcmf** [comment] 2016-03-22 16:53
Thank you @craigh! The MediaModule is still using the Zikula 1.3 installer and version classes.

**Closed by cmfcmf** 2016-03-22 16:53 UTC

**Comment by cmfcmf** [comment] 2016-03-22 16:54
refs https://github.com/cmfcmf/MediaModule/issues/6

**Comment by craigh** [comment] 2016-03-22 18:56
> The MediaModule is still using the Zikula 1.3 installer and version classes.

curious to know if MM installs correctly now or not. perhaps other core bugs with BC?

**Comment by craigh** [comment] 2016-03-22 20:21
recommend re-opening this ticket. CMM will not currently install on 1.4.2.

The problem is that the core is no longer prepared for a Core-1.4.x type module with a 1.3 type installer. While this might be worked around, I'm not sure the best course of action is to do that. It might be best just to "fix" CMM instead as it is likely the only module in such a circumstance.

I doubt the generator creates modules like this, so I don't think that would be an issue (@Guite).

**Comment by craigh** [comment] 2016-03-26 11:52
refs https://github.com/zikula/core/issues/2831

I guess I was wrong about too many modules "in the wild" with this. I guess I will refactor the core :cry: :sob: :cry: :sob: :cry: :sob: :cry: :sob: :cry: :sob: :cry: :sob: :cry: :sob: :cry: :sob: :cry: :sob:

**Comment by craigh** [comment] 2016-03-26 12:13
This is fixed - 1.1.0 should install on 1.4.2 now. but 1.1.1 is better ;-)
